### ISSUE TITLE
Error masking bit 6 of the hour when getting a 24 hour time?

### ISSUE THREAD

**Issue by davsav** [pangopi/micropython-DS3231-AT24C32#1]
I think there is an error in Line 103 of the code file ds3231.py when getting the time from the clock where you mask bit 6 of the hour by anding it with 0x9f as I think it should be 0xbf to mask the 12/24 hour bit.

**Comment by pangopi** [comment]
Thanks @davsav for your in depth reporting. Have pushed the commit as per your suggestion. Cheers!
