### ISSUE TITLE
Problem with SQW / FREQ_1

### ISSUE THREAD

**Issue by x48x4b** [pangopi/micropython-DS3231-AT24C32#3]
Hi

SQW / FREQ_1 does not work.

The Problem is Line 148 ("   if not freq:") in ds3231.py.
Because FREQ_1 = 0 ( and this is treated as "False").

Best regards

**Comment by Bredahl** [comment]
Perhaps not the most elegant solution
but I solved it like this
     FREQ_1 = const(4)
     FREQ_1024 = const(1)
     FREQ_4096 = const(2)
     FREQ_8192 = const(3)
     SQW_32K = const(1)


     def square_wave(self, freq=None):

         if freq is None:
             return self.i2c.readfrom_mem(self.addr, CONTROL_REG, 1)[0]

         if not freq:
             # Set INTCN (bit 2) to 1 and both ALIE (bits 1 & 0) to 0
             self.i2c.readfrom_mem_into(self.addr, CONTROL_REG, self._buf)
             self.i2c.writeto_mem(self.addr, CONTROL_REG, bytearray([(self._buf[0] & 0xf8) | 0x04]))
         else:
             if freq == 4:
                freq = 0
             # Set the frequency in the control reg and at the same time set the INTCN to 0
             self.i2c.readfrom_mem_into(self.addr, CONTROL_REG, self._buf)
             self.i2c.writeto_mem(self.addr, CONTROL_REG, bytearray([(self._buf[0] & 0xe3) | (freq << 3)]))
         return True

**Comment by Bredahl** [comment]
Correction I do not know how "otherwise"
has slipped in

FREQ_1 = const(4)
FREQ_1024 = const(1)
FREQ_4096 = const(2)
FREQ_8192 = const(3)
SQW_32K = const(1)





def square_wave(self, freq=None):

     if freq is None:
         return self.i2c.readfrom_mem(self.addr, CONTROL_REG, 1)[0]

     if not freq:
         # Set INTCN (bit 2) to 1 and both ALIE (bits 1 & 0) to 0
         self.i2c.readfrom_mem_into(self.addr, CONTROL_REG, self._buf)
         self.i2c.writeto_mem(self.addr, CONTROL_REG, bytearray([(self._buf[0] & 0xf8) | 0x04]))
     else:
         if freq == 4:
            freq = 0
         # Set the frequency in the control reg and at the same time set the INTCN to 0
         self.i2c.readfrom_mem_into(self.addr, CONTROL_REG, self._buf)
         self.i2c.writeto_mem(self.addr, CONTROL_REG, bytearray([(self._buf[0] & 0xe3) | (freq << 3)]))
     return True
