### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by AvocadoKings** [pangopi/micropython-DS3231-AT24C32#4]
Hey, i've recently bought a ds3231 rtc and i saw this librarie for it. however, when trying to read or write anything it give me an error: OSError: [Errno 110] ETIMEDOUT.
is this a ecript error or am i just dumb. how would i fix this?

**Comment by pangopi** [comment]
Have you tried running the code as provided in the readme? If that works, please share your code, micropython version and hardware you are using. And full error log if possible.

**Comment by AvocadoKings** [comment]
it was my fault... i thought that Pin(4) and Pin(5) meant d4 and d5 and not GPIO 4 and GPIO 5... i'm stupid af
